### ISSUE TITLE
[META] create mailing list

### ISSUE THREAD

**Issue by patcon** [dougestey/topoli#1]
Happy to do this, as I've set up a few, and there are some config gotchas. Assuming Google Groups is the way to go. The name can be changed fwiw, so no worries about nailing it down first :)

How about "to-city-hall-dev"? Yay? Nay?

**Comment by dougestey** [comment]
I'd vote for toronto-municipal-dev - "toronto" because it's a bit more semantically clear, "municipal" to relax the restriction on it only pertaining to city hall.

**Comment by patcon** [comment]
:+1: can always change the name if the scope widens beyond toronto

**Comment by dougestey** [comment]
Let me know once you've created it and we can close this out.

**Comment by patcon** [comment]
Done and done:
https://groups.google.com/forum/#!forum/toronto-municipal-dev

Sent you an invite
